feat: support lrucache
api7/envoy-apisix pull request #24
Opened 2020-12-28 08:00 UTC by nic-chen

2020-12-28 08:27 UTC, membphis requested changes

2020-12-28 08:27 UTC, membphis commented on lua/deps/resty/lrucache/pureffi.lua
> +-- Copyright (C) Yichun Zhang (agentzh)
remove this file

2020-12-28 08:27 UTC, membphis commented on lua/deps/resty/lrucache.lua
> +-- Copyright (C) Yichun Zhang (agentzh)
added to `licenses` folder

2020-12-28 13:32 UTC, tokers commented
I think we should build the tests from now on.

2020-12-28 13:46 UTC, membphis commented
> I think we should build the tests from now on.

yes, related issue: https://github.com/api7/envoy-apisix/issues/16

2021-01-13 04:30 UTC, membphis approved these changes

2021-01-13 04:31 UTC, merged